### ISSUE TITLE
Separate appengine/datastore to reduce dependencies

### ISSUE THREAD

**Issue by blitzrk** [vmihailenco/msgpack#116]
Can `appengine.go` be moved to a subpackage (aka github.com/vmihailenco/msgpack/appengine) so that tools like govend can prune the fairly heavyweight google.golang.org/appengine/datastore dependency?

It would require users to `_` (underscore) import it instead of just relying on build tags, but since most users won't need it, it'll cut down binary size and number of vendored packages.

I can send in a simple PR, but I haven't used appengine before, so I won't be able to test out that part right away.

Edit: Of course, this would be a breaking change for appengine users, so this wouldn't be easy to implement right away. Maybe I'll focus on a PR for govend that allows specific build tags to be ignored.

**Comment by vmihailenco** [comment]
I think fixing govend is much better approach. Because I use godep and it does not have any issues with eliminating `google.golang.org/appengine` dependency.

**Comment by gabriel** [comment]
I think this might be worth reconsidering now that go modules are here?

**Comment by vmihailenco** [comment]
We can do that for v5, but I doubt that moving it to a subpackage changes anything for go.mod. AFAIK go.mod includes everything it can find but that does not mean that the package is used / required.

@gabriel what do you try to improve here?

**Comment by gabriel** [comment]
I think if you include msgpack in your project you might get appengine as an indirect dependency in go.mod.
It's unclear to me why sometimes is shows as an `//indirect` and sometimes it's not present in go.mod at all.
For example, if I `go mod tidy` it gets removed, but if I `go get -u` it gets included back.

Also showing the `go mod graph` always includes appengine and all it's dependencies as well as `go mod why `.

```shell
> go mod why google.golang.org/appengine
# google.golang.org/appengine
github.com/keys-pub/keys/keyring
github.com/vmihailenco/msgpack/v4
google.golang.org/appengine/datastore
google.golang.org/appengine
```

I am trying to keep what dependencies show up to a minimum in a particular project I am using just because it's in the security/privacy space and want visibility of dependencies to be really obvious and having appengine show up (even if indirect and unused) could be confusing, if that makes sense.

**Comment by vmihailenco** [comment]
I don't read much about go mod, but I believe it tries to record all potential dependencies just in case to be able to properly resolve version conflicts. It does not mean that dependency is actually used. For example, the whole appengine.go file in this repo has `// +build appengine` so it is not even getting compiled unless you are using appengine.
