### ISSUE TITLE
uint32 encoding issue

### ISSUE THREAD

**Issue by sudeep9** [vmihailenco/msgpack#134]
Is there any reason why a `uint32` value (when stored as interface{})  is encoded as `uint64` although the msgpack spec supports `uint32`? For reference link to the [spec](https://github.com/msgpack/msgpack/blob/master/spec.md#formats).

To be more specific:

```go
n := uint32(10)
var v interface{} = n
```

Now if `v` is Marshaled it will be get encoded as `uint64`

**Comment by sudeep9** [comment]
Here is the test which you can execute readily:

```
func TestUint32(t *testing.T) {
	n := uint32(10)
	v := []interface{}{n}

	buf, err := msgpack.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}

	var x interface{}

	err = msgpack.Unmarshal(buf, &x)
	if err != nil {
		t.Fatal(err)
	}

	x2 := x.([]interface{})

	if reflect.TypeOf(v[0]) != reflect.TypeOf(x2[0]) {
		t.Fatalf("Type mismatch, expected %v, got %v", reflect.TypeOf(v[0]), reflect.TypeOf(x2[0]))
	}

}

**Comment by vmihailenco** [comment]
There are 2 unrelated issues here:
- you are decoding into interface{} and for simplicity lib returns only int64 and uint64 when decoding numbers. If you need uint32 - replace interface{} with uint32.
- small uint32 numbers are encoded as uint8 (or just small number) to save space. Exact type is loosed, but it does not matter usually because you can decode number into int8/int16/int32/int64 as you need.

I agree that it is a bit confusing, but I think this is the right behavior that does not cause any problems in practise.
