### ISSUE TITLE
Support json struct tags when there is no msgpack tag

### ISSUE THREAD

**Issue by galdor** [vmihailenco/msgpack#149]
The package currently only supports `msgpack` tags. However it's not uncommon to support both JSON and MsgPack encodings in an application, especially since MsgPack is officially described as being "like JSON".

It would be really simple to support `json` tags if the `msgpack` tag is not set for a struct member. Of course this behaviour could be made optional based on a setting in decoders.

**Comment by gsamokovarov** [comment]
Actually, I would benefit from this in my current project, where we have structs generated from a swagger schema, and it would be really convenient for us, if we can support that. The `json` tags are quite common and may be a useful fallback if the `msgpack` tags are not available.

@vmihailenco are you interested in such PRs?

**Comment by vmihailenco** [comment]
I would accept such PR if:
- such behavior is optional and does not break backwards compatibility
- code is reasonably small

Personally I don't see a use case for such feature in my projects, because JSON tags are usually used to rename `GoName` to `js_name` and I don't think it is important/useful enough for msgpack...

**Comment by gsamokovarov** [comment]
Hey @vmihailenco, I have opened the PR for discussion. The change is pretty short, but I do understand your concerns. That said, for us it's really useful, because we serialize code that is generated from another tool and it's not that easy for us to annotate those structs further more with the `msgpack` tag.

**Comment by vmihailenco** [comment]
Sorry for delay, but finally this should be addressed in v3.2.7
