### ISSUE TITLE
Unmarshal an empty time object provides a problematic timezone

### ISSUE THREAD

**Issue by aviadl** [vmihailenco/msgpack#332]
Unmarshal a byte array that was generated by marshaling an empty time struct
If the unmarshal will receive an interface, this interface will eventually contain an empty time struct but with LMT timezone (that doesnt work properly in many cases)
If the unmarshal will receive a time struct, this will work properly 
## Expected Behavior

empty time object in utc timezone
## Current Behavior
empty time object in LMT timezone
## Possible Solution

add tm.isZero case to the flow of unmarshaling from interface 
It does exists if a typed time struct is provided

## Steps to Reproduce

See the following unit test:
```
func TestEmptyTimeMarshalWithInterface(t *testing.T) {
	a := time.Time{}
	b, err := msgpack.Marshal(a)
	if err != nil {
		t.Fatal(err)
	}
	var out interface{}
	err = msgpack.Unmarshal(b, &out)
	if err != nil {
		t.Fatal(err)
	}
	name, _ := out.(time.Time).Zone()
	if name != "UTC" {
		t.Fatal("Got wrong timezone")
	}

	var out2 time.Time
	err = msgpack.Unmarshal(b, &out2)
	if err != nil {
		t.Fatal(err)
	}
	name, _ = out2.Zone()
	if name != "UTC" {
		t.Fatal("Got wrong timezone")
	}
}
```

**Comment by pascal-zarrad** [comment]
Experiencing the same issue when using go-redis/cache.
Had to switch over to an alternative (JSON) as a workaround for now due to the issue.

**Comment by aviadl** [comment]
@pascal-zarrad you can check my PR above

**Comment by jaimem88** [comment]
https://github.com/eko/gocache recently upgraded to v5, and we are trying to upgrade the dependency as well in https://gitlab.com/gitlab-org/container-registry/-/merge_requests/1442.

Now we are encountering a similar issue where the time.Location is set as time.Local instead of UTC -> https://gitlab.com/gitlab-renovate-forks/container-registry/-/jobs/5419691095, see extract from the test output

```
expected:  DeletedAt:sql.NullTime{Time:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC)
actual:       DeletedAt:sql.NullTime{Time:time.Date(1, time.January, 1, 0, 0, 0, 0, time.Local)
```

It's not the worst as the time is still kept as zero but our test fail when checking for equality.

cc @aviadl @vmihailenco
