### ISSUE TITLE
Marshal fatals if value is channel / struct contains channel

### ISSUE THREAD

**Issue by moogle19** [vmihailenco/msgpack#48]
In my opinion it would be nicer, if an error was returned.

**Comment by vmihailenco** [comment]
Partially addressed by https://github.com/vmihailenco/msgpack/pull/49 - msgpack should panic on channel any more. I can also skip `chan` and `func` in structs by default since I doubt we can something meaningful with channels and functions (now can you annotate such struct fields with `msgpack:"-"`). What do you think?

**Comment by moogle19** [comment]
Looks good! ;)
